version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: courseeditor-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CourseEditorDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped


  server:
    build: 
      context: .
      dockerfile: /CourseEditor.Server/Dockerfile
    container_name: courseeditor-server
    depends_on:
      - postgres
    ports:
      - "5010:5010"
    environment:
      ConnectionStrings__db: "Host=postgres;Port=5432;Database=CourseEditorDb;Username=postgres;Password=postgres"
    restart: unless-stopped

    

volumes:
  pgdata: